export const PRESS_AND_MEDIA = [
  {
    mainImg: "/images/common/glowGetter.png",
    subImg: "/images/common/indianExpress.png",
    company: "Times of India",
    title: "Be a ‘glow’ getter",
    content: "It’s that time of the year again – the time when you take out your shiny sarees or pull out that embroidered confection to be party-ready. And you must face the festivities with a glow that just won’t quit",
    externalLink: "https://timesofindia.indiatimes.com/life-style/beauty/be-a-glow-getter/articleshow/71439927.cms?",
  },
  {
    mainImg: "https://images.indianexpress.com/2019/10/winter-hair-GettyImages-507460990.jpg",
    subImg: "/images/common/newIndianExpress.png",
    company: "The New Indian Express",
    title: "This is why your hair is often oily during winters",
    content: "Having a good hair day can be a tricky affair. You might be in a jolly mood but your hair might just act weird all the time, especially in winters. Even after regular washes, your hair might end up",
    externalLink: "https://indianexpress.com/article/lifestyle/life-style/oily-hair-winters-causes-treatment-haircare-tips-6094919/",
  },
  {
    mainImg: "https://images.indianexpress.com/2019/11/pregnancy-hair.jpg",
    subImg:"/images/common/indianExpress.png",
    company: "Indian Express",
    title: "Pregnancy tips: 5 effective and natural ways for hair care",
    content: "Pregnancy hair care tips: It is advisable to keep away from artificial hair colours as some of them may contain harmful chemicals or have strong aromas",
    externalLink: "https://indianexpress.com/article/parenting/health-fitness/pregnancy-tips-effective-natural-ways-for-hair-care-6121388/",
  },
  {
    mainImg: "https://www.healthshots.com/wp-content/uploads/2019/11/photo.1503667663817.f57326084f09.jpg",
    subImg: "/images/common/indianExpress.png",
    company: "Hindustan Times",
    title: "Love sweating it out at the gym?",
    content: "They say, there are no free lunches in life. Unfortunately, your workouts are no exception to this rule. Simply because that much-desired inch-loss comes at a steep price of hard work and well—some skin damage too",
    externalLink: "https://www.healthshots.com/beauty/skin-care/love-sweating-it-out-at-the-gym-then-this-dermat-approved-post-workout-skincare-guide-is-for-you/",
  },
  {
    mainImg: "https://www.healthshots.com/wp-content/uploads/2019/11/potatoes-1585060_960_720.jpg",
    subImg: "/images/common/newIndianExpress.png",
    company: "Hindustan Times",
    title: "Here’s what potatoes can do for your under-eye area",
    content: "Ladies, the solution to your under-eye problems is in your kitchen--namely in your vegetable basket. Because there ain’t nothing that the humble aloo can’t do. From messy home remedies to injectable fillers and fancy eye creams",
    externalLink: "https://www.healthshots.com/beauty/natural-cures/from-combating-puffiness-to-reducing-dark-circles-here-is-what-potatoes-can-do-for-your-under-eye-area/",
  },
  {
    mainImg: "http://static.businessworld.in/article/article_extra_large_image/1574250962_rx7G5H_FotoJet_1_.jpg",
    subImg: "/images/common/indianExpress.png",
    company: "Business World",
    title: "Luxurious furtherance in Dermatology",
    content: "High-end skin treatments such as Vampire Facials have become quite popular with the elite. These fancy treatments could cost anything up to Rs 10 lakh per visit depending on the clinics. Dr Jamuna Pai, founder of Skinlab and Dr Priyanka Reddy, founder of DNA Skin clinic",
    externalLink: "http://bwhealthcareworld.businessworld.in/article/Luxurious-furtherance-in-Dermatology/20-11-2019-179269/",
  },
];